image: docker:stable

stages:
    - build
    - test
    - push-artifacts
    - deploy

variables:
  # When using dind, it's wise to use the overlayfs driver for improved performance.
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  CLOUD_PROJECT: mab-testing
  PROJECT_NAME: kuard
  APP_NAME: kuard
  CLUSTER_NAME: devfest
  CLUSTER_ZONE: europe-west3-c
  IMAGE_REPO: eu.gcr.io/${CLOUD_PROJECT}/${PROJECT_NAME}/${APP_NAME}

services:
  - docker:dind

build-make:
  stage: build
  before_script: 
    - apk add --update alpine-sdk
  script:
    - cd kuard
    - time make build 
  artifacts:
   paths:
    - kuard/bin/


test:
  stage: test
  script:
    # TODO: add tests lol
    - echo "all ok"
    
build-n-publish-image:
  before_script:
   - apk add --update make ca-certificates openssl python curl bash tree git jq update-ca-certificates
   - | 
      cd / && wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz && \
      tar zxvf google-cloud-sdk.tar.gz && \
      ./google-cloud-sdk/install.sh --usage-reporting=false --path-update=true

  stage: push-artifacts
  only:
    - master
  script: 
    # Write our GCP service account private key into a file.
    - echo "$GCLOUD_SERVICE_KEY" | base64 -d > ./gcloud-service-key.json
    - /google-cloud/sdk/bin/gcloud auth configure-docker
    - docker build --pull --cache-from $IMAGE_REPO:latest -t $IMAGE_REPO:latest -t $IMAGE_REPO:$CI_BUILD_REF .
    - docker push $IMAGE_REPO:latest 
    - docker push $IMAGE_REPO:$CI_BUILD_REF

deploy-manifests:
  stage: deploy
  only:
    - master
  script:
    - kubectl apply -f k8s/
