image: docker:stable

stages:
    - build
    - test
    - push-artifacts
    - deploy

variables:
  # When using dind, it's wise to use the overlayfs driver for improved performance.
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://127.0.0.1:2375
  CLOUD_PROJECT: mab-testing
  CLUSTER_NAME: devfest
  CLUSTER_ZONE: europe-west3-c

services:
  - docker:dind

build-make:
  stage: build
  script:
    - cd kuard
    - make build 

build-image:
  stage: push-artifacts
  only:
    - master
  script: 
    # Write our GCP service account private key into a file.
    - echo "$GCLOUD_SERVICE_KEY" | base64 -d > ./gcloud-service-key.json
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest -f  pipeline-builder/Dockerfile -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE

