{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Add to generate certificates for this ingress
    kubernetes.io/tls-acme: 'true'
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  rules:
{{ if eq .Values.namespace "default" }}
    - host: demoapp.revolgy.cloud
      http:
        paths:
          - backend:
              serviceName: demoapp
              servicePort: 80
            path: /
{{ else }}
    - host: demoapp-{{ .Values.namespace }}.revolgy.cloud
      http:
        paths:
          - backend:
              serviceName: demoapp
              servicePort: 80
            path: /
{{ end }}
  tls:
    - hosts:
{{ if eq .Values.namespace  "default" }}
        - "demoapp.revolgy.com"
{{ else }}
        - "demoapp-{{ .Values.namespace }}.revolgy.com"
{{ end }}
      secretName: example-tls
{{- end }}
